- group: 查询类功能
  list:
    - icon: weihua
      title: "#未花"
      desc: 查看未花的角评攻略
    - icon: abiduosi
      title: "#星野"
      desc: 查看星野的角评
    - icon: geheina
      title: "#日奈"
      desc: 查看日奈的角评
    - icon: qianxi
      title: "#优香"
      desc: 查看优香的角评
    - icon: shengsanyi
      title: "#响"
      desc: 查看响的角评
    - icon: aliusi
      title: "#纱织"
      desc: 查看纱织的角评
    - icon: waerjili
      title: "#吹雪"
      desc: 查看吹雪的角评
    - icon: baigui
      title: "#小狐狸"
      desc: 查看泉奈的角评
    - icon: shanhaijing
      title: "#教官"
      desc: 查看瞬的角评
    - icon: srt
      title: "#水宫子"
      desc: 查看泳装宫子的角评
- group: 
  list:
    - icon: qipao
      title: "#1-1"
      desc: 查看1-1的关卡攻略
    - icon: quannai
      title: "#1-1H"
      desc: 查看1-1hard的关卡攻略
    - icon: qqq
      title: "#60秒看世界"
      desc: 看新闻
    - icon: chahui
      title: "无"
      desc: 无
    - icon: nuoya
      title: "无"
      desc: 无
    - icon: teyixianxiang
      title: "无"
      desc: 无
    - icon: xinnai
      title: "无"
      desc: 无
    - icon: yantaohui
      title: "无"
      desc: 无
    - icon: wanmo
      title: "无"
      desc: 无
    - icon: yilvbo
      title: "无"
      desc: 无
    - icon: fengji
      title: "无"
      desc: 无
- group: 其他功能
  list:
    - icon: xialai
      title: "#学生列表"
      desc: "查看所有学生"
    - icon: xueshenghui
      title: "#BA插件更新"
      desc: "更新"
    - icon: xueshenghui
      title: "凑对称"
      desc: "氵"